# Generated by Django 3.2.13 on 2022-05-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_auto_20220528_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='media',
            field=models.DecimalField(blank=True, decimal_places=1, default=2.5, max_digits=2),
            preserve_default=False,
        ),
    ]
