# Generated by Django 3.2.13 on 2022-05-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_alter_curso_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='media',
            field=models.FloatField(),
        ),
    ]
