# Generated by Django 3.2.13 on 2022-05-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_alter_curso_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='media',
            field=models.FloatField(blank=True),
        ),
    ]
